namespace Pastel.Parser.ParseNodes
{
    internal enum ExpressionType
    {
        BRACKET_INDEX,
        CAST,
        COMPILE_TIME_FUNCTION_REFERENCE,
        CONSTRUCTOR_INVOCATION,
        CONSTRUCTOR_REFERENCE,
        CORE_FUNCTION_REFERENCE,
        CORE_FUNCTION_INVOCATION,
        DOT_FIELD,
        ENUM_REFERENCE,
        EXTENSIBLE_FUNCTION_INVOCATION,
        EXTENSIBLE_FUNCTION_REFERENCE,
        FUNCTION_INVOCATION,
        FUNCTION_POINTER_INVOCATION,
        FUNCTION_REFERENCE,
        INLINE_CONSTANT,
        INLINE_INCREMENT,
        NAMESPACE_REFERENCE,
        OP_CHAIN,
        OP_PAIR,
        STRING_CONCATENATION,
        UNARY_OP,
        VARIABLE,
    }
}
